database:
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "1234"
    dbname: "ginchat"
    charset: "utf8mb4"
    max_open_conns: 100  # 最大连接数
    max_idle_conns: 10   # 空闲连接池大小
    timeout: "10s"       # 连接超时时间
  redis:
    host: "127.0.0.1"    # Redis服务器地址
    port: 6379           # 端口
    password: ""         # 密码（没有密码留空）
    db: 0                # 数据库编号（0-15）
    pool_size: 10        # 连接池大小
    min_idle_conns: 2    # 最小空闲连接数
    dial_timeout: "5s"   # 连接超时
    read_timeout: "3s"   # 读取超时
    write_timeout: "3s"  # 写入超时
